###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-09-19 11:51:16
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-09-19 11:52:33
###############################################################

invokables:
	company_data_fieldset_form : Data/Form/CompanyDataFieldsetForm
	company_data_create_form : Data/Form/CompanyDataCreateForm
	company_data_edit_form : Data/Form/CompanyDataEditForm
	company_data_search_form : Data/Form/CompanyDataSearchForm