invokables:
	company_data_timeline_template : Data/Template/CompanyDataTimelineTemplate

	company_data_search_template	: Data/Template/CompanyDataSearchTemplate
	company_data_view_template		: Data/Template/CompanyDataViewTemplate
	company_data_create_template	: Data/Template/CompanyDataCreateTemplate
	company_data_update_template	: Data/Template/CompanyDataUpdateTemplate
	company_data_delete_template	: Data/Template/CompanyDataDeleteTemplate

shared :
	company_data_search_template	: true
	company_data_view_template		: true
	company_data_create_template	: true
	company_data_update_template	: true
	company_data_delete_template	: true